services:

  frontend:
    build:
      context: ./frontend
    container_name: vastites-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"

  backend:
    build:
      context: ./backend/vastites-cms
    container_name: vastites-backend
    restart: unless-stopped
    env_file:
      - ./backend/vastites-cms/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:1338:1337"
